### PR TITLE
Add possibility to set custom mailers for DKIM.

### PR DESCRIPTION
**Pull request by woodspire**
This way, it's possible to use DKIM with mailchimp, mandrill, postmark, ses, etc ...

### CODE REVIEW

**Comment by simonschaufi** [comment]
Thank you for your contribution. Please make sure the code style looks good.

**Comment by maurice-ellis** [comment]
@simonschaufi , is it possible to add "mail" for PHP Mail to that list of arrays? I added the option to my code and it worked.

**Comment by maurice-ellis** [comment]
@simonschaufi Great, thanks! Love your package, saved me a lot of time and effort

**Comment by simonschaufi** [comment]
@maurice-ellis thank you very much for these nice words! If you feel like to give something back, you can sponsor me with a little tip through Github, PayPal or bymeacoffee. Links are in the readme page.

**Comment by Iaotle** [comment]
Could someone merge this? The ability to set custom mailers has still not been implemented. The whole PR is three lines long.

**Pull request closed without merging**
