### PR TITLE
Update to Laravel 8.*

### PR DESCRIPTION
**Pull request by Lipa77**
Change illuminate/mail version to 8.* - should work with Laravel 8

### CODE REVIEW

**Comment by simonschaufi** [comment]
To be backwards compatible, I changed the line slightly. Can you confirm that the code really works with laravel 8?

**Comment by Lipa77** [comment]
Unfortunately, I don't know how to check it :(

**Comment by simonschaufi** [comment]
- In your composer.json replace `"simonschaufi/laravel-dkim": "^1.0",` with `"simonschaufi/laravel-dkim": "@dev",`
- create a `packages` folder and put this repository in it with a subfolder like: `packages/laravel-dkim`
- adjust the composer.json of my package (with your patch)
- add this to your root composer.json:
```json
    "repositories": [
        { "type": "path", "url": "./packages/*" }
    ],
```
- execute: `rm -rf vendor/simonschaufi`
- execute: `composer update`. Now my package should be symlinked into the vendor folder

**Comment by Lipa77** [comment]
I have issue with local package: Composer still use Your package from "simonschaufi/laravel-dkim"  (instead the local one) ...

Local package is in folder:
`/packages/simonschaufi/laravel-dkim`

My composer file:
```json
    "repositories": {
        "laravel-dkim": {
            "type": "path",
            "url": "/packages/simonschaufi/laravel-dkim",
            "options": {
                "symlink": true
            }
        }
    },
    "require": {      
        "simonschaufi/laravel-dkim": "@dev"
    },
    "config": {
        "preferred-install": "source",
        "sort-packages": true,
        "optimize-autoloader": true
    },
    "minimum-stability": "dev",
    "prefer-stable": true
 ```

**Do You know what is wrong ????**

**Comment by simonschaufi** [comment]
Please use the path like I wrote it!

**Comment by Lipa77** [comment]
I tried it before and does't work for me. So right now I'm looking for the solution on [https://stackoverflow.com/questions/64014708/how-to-use-local-composer-packages-in-laravel](url)

**Comment by simonschaufi** [comment]
This is my root composer.json and it works like this:

```json
{
    "name": "laravel/laravel",
    "type": "project",
    "description": "The Laravel Framework.",
    "keywords": [
        "framework",
        "laravel"
    ],
    "license": "MIT",
    "repositories": [
        { "type": "path", "url": "./packages/*" }
    ],
    "require": {
...
        "simonschaufi/laravel-dkim": "@dev",
...
    },
    "require-dev": {
...
    },
    "config": {
        "optimize-autoloader": true,
        "preferred-install": "dist",
        "sort-packages": true
    },
    "extra": {
        "laravel": {
            "dont-discover": []
        }
    },
    "autoload": {
        "psr-4": {
            "App\\": "app/"
        },
        "classmap": [
            "database/seeds",
            "database/factories"
        ]
    },
    "autoload-dev": {
        "psr-4": {
            "Tests\\": "tests/"
        }
    },
    "minimum-stability": "dev",
    "prefer-stable": true,
    "scripts": {
        "post-autoload-dump": [
            "Illuminate\\Foundation\\ComposerScripts::postAutoloadDump",
            "@php artisan package:discover --ansi"
        ],
        "post-root-package-install": [
            "@php -r \"file_exists('.env') || copy('.env.example', '.env');\""
        ],
        "post-create-project-cmd": [
            "@php artisan key:generate --ansi"
        ]
    }
}
```

**Comment by Lipa77** [comment]
When I use `"url": "./packages/*"` i got an error:
` [ErrorException]
  Trying to access array offset on value of type null
`

**Comment by simonschaufi** [comment]
which version of composer are you using?

**Comment by Lipa77** [comment]
You have absolutely right: the problem was because I used old version of Composer. 
After composer update local package was installed correctly :)

Tomorrow I will check a new version of Your package and let You know.
Thanks for Your support!

**Comment by Lipa77** [comment]
Checked on laravel 8.6.0 and illuminate/mail 8.5: everything works correctly :)

**Pull request merged**
